name: migrate-db

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install
        working-directory: api

      - name: Run prisma migrate
        run: bunx prisma migrate deploy
        working-directory: api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
