name: migrate-db

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: self-hosted 

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - run: bunx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
